# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  agent: zhaoxiaotong

variables:
  buildConfiguration: 'Release'

steps:
- script: |
   git config user.email "callmetongge@outlook.com"
   
   git config user.name "Xiaotong.Zhao"
    
   git pull https://github.com/XiaotongZhao/JustLearn.git --no-rebase 
    
   git push https://github.com/XiaotongZhao/JustLearn.git refs/remotes/origin/main:refs/heads/main
  displayName: 'Sync to Github'
